<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns='http://www.w3.org/1999/xhtml' xml:lang='en' lang='en'>
<head>
<title>psha/gct-doc - Unnamed repository; edit this file 'description' to name the repository.</title>
<meta name='generator' content='cgit v0.8.3.3'/>
<meta name='robots' content='index, nofollow'/>
<link rel='stylesheet' type='text/css' href='/cgit-static/cgit.css'/>
<link rel='shortcut icon' href='/favicon.ico'/>
<link rel='alternate' title='Atom feed' href='http://psha.org.ru/cgit/psha/gct-doc/atom/Makefile?h=master' type='application/atom+xml'/>
</head>
<body>
<div id='cgit'><table id='header'>
<tr>
<td class='logo' rowspan='2'><a href='/cgit/'><img src='/cgit-static/cgit.png' alt='cgit logo'/></a></td>
<td class='main'><a href='/cgit/'>index</a> : <a title='psha/gct-doc' href='/cgit/psha/gct-doc/'>psha/gct-doc</a></td><td class='form'><form method='get' action=''>
<select name='h' onchange='this.form.submit();'>
<option value='master' selected='selected'>master</option>
</select> <input type='submit' name='' value='switch'/></form></td></tr>
<tr><td class='sub'>Unnamed repository; edit this file 'description' to name the repository.</td><td class='sub right'>psha</td></tr></table>
<table class='tabs'><tr><td>
<a href='/cgit/psha/gct-doc/'>summary</a><a href='/cgit/psha/gct-doc/refs/'>refs</a><a href='/cgit/psha/gct-doc/log/Makefile'>log</a><a class='active' href='/cgit/psha/gct-doc/tree/Makefile'>tree</a><a href='/cgit/psha/gct-doc/commit/Makefile'>commit</a><a href='/cgit/psha/gct-doc/diff/Makefile'>diff</a></td><td class='form'><form class='right' method='get' action='/cgit/psha/gct-doc/log/Makefile'>
<select name='qt'>
<option value='grep'>log msg</option>
<option value='author'>author</option>
<option value='committer'>committer</option>
<option value='range'>range</option>
</select>
<input class='txt' type='text' size='10' name='q' value=''/>
<input type='submit' value='search'/>
</form>
</td></tr></table>
<div class='path'>path: <a href='/cgit/psha/gct-doc/tree/'>root</a>/<a href='/cgit/psha/gct-doc/tree/Makefile'>Makefile</a></div><div class='content'>blob: 341651cbfc509bcf54eb4b120704daa7501d06fd (<a href='/cgit/psha/gct-doc/plain/Makefile'>plain</a>)
<table summary='blob content' class='blob'>
<tr><td class='linenumbers'><pre><a class='no' id='n1' name='n1' href='#n1'>1</a>
<a class='no' id='n2' name='n2' href='#n2'>2</a>
<a class='no' id='n3' name='n3' href='#n3'>3</a>
<a class='no' id='n4' name='n4' href='#n4'>4</a>
<a class='no' id='n5' name='n5' href='#n5'>5</a>
<a class='no' id='n6' name='n6' href='#n6'>6</a>
<a class='no' id='n7' name='n7' href='#n7'>7</a>
<a class='no' id='n8' name='n8' href='#n8'>8</a>
</pre></td>
<td class='lines'><pre><code>DBLATEX_OPTS := -bxetex -P doc.publisher.show=0 -P latex.output.revhistory=0
all: gcodetools-ru.pdf gcodetools-ru.html

%.pdf: %.asciidoc
	a2x -f pdf -v --dblatex-opts="$(DBLATEX_OPTS)" $&lt;

%.html: %.asciidoc
	a2x -f xhtml -v --dblatex-opts="$(DBLATEX_OPTS)" $&lt;
</code></pre></td></tr></table>
</div> <!-- class=content -->
<div class='footer'>generated  by cgit v0.8.3.3 at 2011-08-04 06:36:26 (GMT)</div>
</div> <!-- id=cgit -->
</body>
</html>
